let products=[],cart=JSON.parse(localStorage.cart||"[]");
const $=id=>document.getElementById(id);
async function load(){products=await fetch("/api/products").then(r=>r.json());render();renderCart();}
function render(){ $("products").innerHTML=products.map(p=>{let sale=p.price*(1-p.discount/100);return `<article class="card"><img src="${esc(p.image||'https://via.placeholder.com/600x500')}"><div class="body"><h3>${esc(p.name)}</h3><p>${esc(p.description||"")}</p><div class="price">₹${sale.toFixed(0)} ${p.discount?`<span class="old">₹${p.price}</span>`:""}</div><small>Stock: ${p.stock}</small><br><br><button onclick="add(${p.id})" ${p.stock<1?"disabled":""}>Add to cart</button></div></article>`}).join("")}
function add(id){let x=cart.find(x=>x.id===id);x?x.qty++:cart.push({id,qty:1});localStorage.cart=JSON.stringify(cart);renderCart();openCart()}
function renderCart(){let rows=cart.map(x=>{let p=products.find(p=>p.id===x.id);return p?`<div class="cartRow"><div style="flex:1"><b>${esc(p.name)}</b><br>₹${(p.price*(1-p.discount/100)).toFixed(0)} × ${x.qty}</div><button onclick="change(${p.id},-1)">−</button><button onclick="change(${p.id},1)">+</button></div>`:""}).join("");$("cartItems").innerHTML=rows||"<p>Your cart is empty.</p>";let total=cart.reduce((s,x)=>{let p=products.find(p=>p.id===x.id);return s+(p?p.price*(1-p.discount/100)*x.qty:0)},0);$("total").textContent=total.toFixed(0);$("count").textContent=cart.reduce((s,x)=>s+x.qty,0)}
function change(id,d){let x=cart.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<1)cart=cart.filter(y=>y.id!==id);localStorage.cart=JSON.stringify(cart);renderCart()}
function openCart(){$("cart").classList.add("open")}function closeCart(){$("cart").classList.remove("open")}
async function placeOrder(e){e.preventDefault();if(!cart.length)return alert("Cart empty");let r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer:{name:$("cn").value,email:$("ce").value,phone:$("cp").value,address:$("ca").value},items:cart})});let d=await r.json();if(!r.ok)return alert(d.error||"Order failed");alert(`Order #${d.orderId} placed. Total ₹${d.total}`);cart=[];localStorage.cart="[]";renderCart();closeCart();load()}
async function login(){let r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("ae").value,password:$("ap").value})});let d=await r.json();if(!r.ok)return alert(d.error);showPanel()}
async function showPanel(){$("login").hidden=true;$("panel").hidden=false;renderAdmin();let r=await fetch("/api/admin/orders",{credentials:"same-origin"});if(r.ok){let o=await r.json();$("orders").innerHTML=o.map(x=>`<div class="adminItem"><b>#${x.id} — ₹${x.total}</b><br>${esc(x.customer_name)} · ${esc(x.email)}<br>${esc(x.address)}<br><small>${x.payment_status} / ${x.order_status}</small></div>`).join("")}}
function renderAdmin(){$("adminProducts").innerHTML=products.map(p=>`<div class="adminItem"><b>${esc(p.name)}</b> — ₹${p.price} | ${p.discount}% off | stock ${p.stock}<br><button onclick="edit(${p.id})">✏️ Edit</button> <button onclick="del(${p.id})">🗑️ Delete</button></div>`).join("")}
function edit(id){let p=products.find(p=>p.id===id);$("pid").value=p.id;$("pn").value=p.name;$("pp").value=p.price;$("pd").value=p.discount;$("ps").value=p.stock;$("pi").value=p.image;$("px").value=p.description}
function resetForm(){["pn","pp","pd","ps","pi","px"].forEach(id=>$(id).value="");$("pd").value="0";$("ps").value="0";$("pid").value=""}
async function saveProduct(e){e.preventDefault();let id=$("pid").value;let body={name:$("pn").value,price:$("pp").value,discount:$("pd").value,stock:$("ps").value,image:$("pi").value,description:$("px").value};let r=await fetch("/api/admin/products"+(id?"/"+id:""),{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify(body)});if(!r.ok)return alert("Save failed");resetForm();await load();showPanel()}
async function del(id){if(!confirm("Delete product?"))return;let r=await fetch("/api/admin/products/"+id,{method:"DELETE",credentials:"same-origin"});if(!r.ok)return alert("Delete failed");await load();showPanel()}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
load();
async function logout(){await fetch("/api/admin/logout",{method:"POST",credentials:"same-origin"});location.reload();}
